### ISSUE TITLE
Problems in building the Purkinje cell

### ISSUE THREAD

**Issue by dariosannino** [dbbs-lab/arborize#29]
I found some problems with the Purkinje cell. After the last release, I am not able anymore to build the cell. I will give you the definition and the commands that I am writing in the CLI:

```from arborize import define_model

definitionPCWT = define_model({
    "synapse_types": {
        "AMPA": {
            "mechanism": "AMPA",
            "parameters": {
                "tau_facil": 54,
                "tau_rec": 35.1,
                "tau_1": 6,
                "gmax": 1200,
                "U": 0.13,
            },
        },
        "GABA": {
            "mechanism": "GABA",
            "parameters": {
                "tau_facil": 4,
                "tau_rec": 15,
                "tau_1": 1,
                "Erev": -70,
                "gmax": 2600,
                "U": 0.35,
            },
        },
    },
    "cable_types": {
        "soma": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "na": {"rev_pot": 60},
                "k": {"rev_pot": -88},
                "h": {"rev_pot": -34.4},
                "ca": {"rev_pot": 137.52625}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.001},
                "Nav1_6": {"gbar": 0.19835422387652},
                "Kv1_1": {"gbar": 0.00185494695569},
                "Kv3_4": {"gkbar": 0.05684366437809},
                "Kir2_3": {"gkbar": 2.100544604e-05},
                "Cav2_1": {"pcabar": 0.0001530123689},
                "Cav3_1": {"pcabar": 4.19659246e-06},
                "Cav3_2": {"gcabar": 0.00067268089296},
                "Cav3_3": {"pcabar": 0.00015401124325},
                "Kca1_1": {"gbar": 0.00877088561313},
                "Kca2_2": {"gkbar": 0.00085748826176},
                "Kca3_1": {"gkbar": 0.00978230722317},
                "HCN1": {"gbar": 0.00192222696826},
                ("cdp5", "CAM"): {"TotalPump": 2e-08},
            },
            "synapses": {
                "GABA": {
                    "mechanism": "GABA",
                    "parameters": {
                        "tau_facil": 4,
                        "tau_rec": 15,
                        "tau_1": 1,
                        "Erev": -70,
                        "gmax": 2600,
                        "U": 0.35,
                    },
                },
            },
        },
        "dendrites": {
            "cable": {
                # "cm": lambda d: (11.510294 * math.exp(-1.376463 * d) + 2.120503),
                # Formula for cm varied from 2 to 6, aprroximated with avg
                "cm": 5.577701084442752,
                "Ra": 122,
            },
            "ions": {
                "na": {"rev_pot": 60},
                "k": {"rev_pot": -88},
                "h": {"rev_pot": -34.4},
                "ca": {"rev_pot": 137.52625},
            },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Kv1_1": {"gbar": 0.00105296938319},
                "Kv1_5": {"gKur": 0.00018237109331},
                "Kv3_3": {"gbar": 0.01192448545734},
                "Kv4_3": {"gkbar": 0.00082020749325},
                "Cav2_1": {"pcabar": 0.001594103024736},
                "Cav3_3": {"pcabar": 0.00013000262047},
                "Kca1_1": {"gbar": 0.03803999223084},
                "HCN1": {"gbar": 2.49811225e-06},
                ("cdp5", "CAM"): {"TotalPump": 5e-08},
            },
            "synapses": {
                "AMPA": {
                    "mechanism": "AMPA",
                    "parameters": {
                        "tau_facil": 54,
                        "tau_rec": 35.1,
                        "tau_1": 6,
                        "gmax": 1200,
                        "U": 0.13,
                    },
                },
            },
        },
        "basal_dendrites": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "na": {"rev_pot": 60}, "k": {"rev_pot": -88}, "ca": {"rev_pot": 137.52625}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Kir2_3": {"gkbar": 1.135399111e-05},
                "Cav3_1": {"pcabar": 4.0066819e-06},
                "Cav3_2": {"gcabar": 0.00194175819441},
                "Kca2_2": {"gkbar": 0.00078534639818},
                "Kca3_1": {"gkbar": 0.00330481139341},
            },
        },
        "sodium_dendrites": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "na": {"rev_pot": 60}, "k": {"rev_pot": -88}, "ca": {"rev_pot": 137.52625}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Kir2_3": {"gkbar": 1.135399111e-05},
                "Cav3_1": {"pcabar": 4.0066819e-06},
                "Cav3_2": {"gcabar": 0.00194175819441},
                "Kca2_2": {"gkbar": 0.00078534639818},
                "Kca3_1": {"gkbar": 0.00330481139341},
                "Nav1_6": {"gbar": 0.01568012827236},
            },
        },
        "aa_targets": {"cable": {}, "ions": {}, "mechanisms": {}},
        "pf_targets": {"cable": {}, "ions": {}, "mechanisms": {}},
        "sc_targets": {"cable": {}, "ions": {}, "mechanisms": {}},
        "AIS": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "na": {"rev_pot": 60}, "k": {"rev_pot": -88}, "ca": {"rev_pot": 137.52625}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Nav1_6": {"gbar": 0.76520432560779},
                "Kv3_4": {"gkbar": 0.01470016164534},
                "Cav2_1": {"pcabar": 0.00028786836482},
                "Cav3_1": {"pcabar": 6.43429659e-06},
                ("cdp5", "CAM"): {"TotalPump": 2e-08},
            },
        },
        "axon": {"cable": {}, "ions": {}, "mechanisms": {}},
        "AIS_K": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "k": {"rev_pot": -88}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Kv1_1": {"gbar": 0.01011038066089},
            },
        },
        "axonmyelin": {
            "cable": {"Ra": 122, "cm": 1.87e-11},
            "ions": {},
            "mechanisms": {"pas": {"e": -61, "g": 5.6e-09}},
        },
        "nodes": {
            "cable": {"Ra": 122, "cm": 1},
            "ions": {
                "na": {"rev_pot": 60}, "k": {"rev_pot": -88}, "ca": {"rev_pot": 137.52625}
                },
            "mechanisms": {
                "Leak": {"e": -61, "gmax": 0.0003},
                "Nav1_6": {"gbar": 0.02749309338198},
                "Kv3_4": {"gkbar": 0.02227585026371},
                "Cav2_1": {"pcabar": 0.00012353396215},
                "Cav3_1": {"pcabar": 1.508814156e-05},
                ("cdp5", "CAM"): {"TotalPump": 5e-07},
            },
        },
    },
})


tagsPC = {
    16: ["axon", "AIS"],
    17: ["axon", "AIS_K"],
    18: ["axon", "axonmyelin"],
    19: ["axon", "nodes"],
    20: ["dendrites", "basal_dendrites"],
    21: ["dendrites", "pf_targets", "sc_targets"],
    22: ["dendrites", "aa_targets", "sc_targets"],
}
```

After the definition I continue in this way:
```
morpho = Morphology.from_swc("Morphologies/PurkinjeCell.swc", tags=tagsPC)
schematic = bsb_schematic(morpho, definitionPCWT)
cell = neuron_build(schematic)
```

And then it returns this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/builders/_neuron.py", line 131, in neuron_build
    schematic.freeze()
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 128, in freeze
    self._flatten_branches(self.roots)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 147, in _flatten_branches
    self._flatten_branches(branch.children)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 147, in _flatten_branches
    self._flatten_branches(branch.children)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 134, in _flatten_branches
    branch.definition = self._makedef(branch.labels)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 160, in _makedef
    return CableType.anchor(
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/definitions.py", line 142, in anchor
    def_.merge(def_right)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/definitions.py", line 147, in merge
    self._mergedict(self.ions, def_right.ions)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/definitions.py", line 154, in _mergedict
    dself[key].merge(dother[key])
AttributeError: 'Ion' object has no attribute 'merge' 
```

Doing a bit of debugging it seems that the error stands in "dendrites". Its ion description is identical to the one of the "soma", but the one of the dendrites give problems. I discovered this removing/commenting the ions in each section, and the only one that gives problems is that of "dendrites". Hope it could help. If there is somenthing wrong in my code let me know, please.
Thank you.

**Comment by Helveg** [comment]
The `Ion` class that I added to fix #28 did not have a `merge` function yet which is required to compose sections with multiple labels. Let me know if it is not fixed on the latest commit.
