### ISSUE TITLE
Purkinje cell does not receive default values of int_con and ext_con

### ISSUE THREAD

**Issue by dariosannino** [dbbs-lab/arborize#32]
Hi, I am still facing some problems when I try to build the Purkinje cell model from the definition.
It seems that the Purkinje cell model does not have default values for int_con and ext_con, whereas the granule cell does have it and I do not need to introduce these values in the definition.

My code is:

```
from arborize import bsb_schematic
from bsb.morphologies import Morphology
from bsb.plotting import plot_morphology
from arborize import neuron_build
import numpy as np
from patch import p

from models.Purkinje_cell.purkinje_cell import definitionPCWT, tagsPC

morpho = Morphology.from_swc(
            "Morphologies/PurkinjeCell.swc", tags=tagsPC)
schematic = bsb_schematic(morpho, definitionPCWT)
cell = neuron_build(schematic)
```

And this is the error that I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/builders/_neuron.py", line 135, in neuron_build
    schematic.freeze()
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 128, in freeze
    self._flatten_branches(self.roots)
  File "/mnt/c/Users/pc/.vscode/Thesis_2/arborize/arborize/schematic.py", line 143, in _flatten_branches
    raise ModelDefinitionError(
arborize.exceptions.ModelDefinitionError: location (0.0) labelled 'soma' misses value for ('na', 'int_con')
```

I am currently using arborize 4.0.0a5 version. Default values are expected to work as for the granule cell model. Can you help me?

Thanks

**Comment by Helveg** [comment]
Default values need to be enabled by passing `use_defaults=True` to the definition
