### ISSUE TITLE
NameError: name 'NotRecordingError' is not defined

### ISSUE THREAD

**Issue by Helveg** [dbbs-lab/arborize#5]
When accessing `cell.Vm` without calling `.record_soma`

**Comment by Helveg** [comment]
Fixed.

```
>>> dbbs_models.GranuleCell().Vm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/GIT/arborize/arborize/core.py", line 96, in __getattr__
    raise NotRecordingError("Trying to read Vm of a cell that is not recording." + " Use `.record_soma()` to enable recording of the soma.")
arborize.exceptions.NotRecordingError: Trying to read Vm of a cell that is not recording. Use `.record_soma()` to enable recording of the soma.
```
